"""Upravené unique klíče

Revision ID: 20451f64ded5
Revises: e7bcb5bfc3cd
Create Date: 2020-08-19 14:34:37.214692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20451f64ded5'
down_revision = 'e7bcb5bfc3cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('connector_rev_group_type_ibfk_2', 'connector_rev_group_type', type_='foreignkey')
    op.drop_constraint('connector_rev_group_type_ibfk_1', 'connector_rev_group_type', type_='foreignkey')
    op.create_foreign_key(None, 'connector_rev_group_type', 'group_of_rev_types', ['id_rev_group'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'connector_rev_group_type', 'revision_types', ['id_rev_type'], ['id'], ondelete='CASCADE')
    op.drop_index('id_acc_center', table_name='devices')
    op.drop_index('id_acc_center', table_name='revision_locations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_acc_center', 'revision_locations', ['id_acc_center'], unique=True)
    op.create_index('id_acc_center', 'devices', ['id_acc_center'], unique=True)
    op.drop_constraint(None, 'connector_rev_group_type', type_='foreignkey')
    op.drop_constraint(None, 'connector_rev_group_type', type_='foreignkey')
    op.create_foreign_key('connector_rev_group_type_ibfk_1', 'connector_rev_group_type', 'group_of_rev_types', ['id_rev_group'], ['id'])
    op.create_foreign_key('connector_rev_group_type_ibfk_2', 'connector_rev_group_type', 'revision_types', ['id_rev_type'], ['id'])
    # ### end Alembic commands ###
