"""Edited Users columns to nullable

Revision ID: 21bf4dd74b72
Revises: 5ab7db83336b
Create Date: 2020-09-01 10:38:46.368512

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '21bf4dd74b72'
down_revision = '5ab7db83336b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True)
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8_bin', length=128),
               nullable=False)
    op.alter_column('users', 'is_enabled',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False)
    # ### end Alembic commands ###
