"""Deleting some fields from revission table

Revision ID: 4a09e2438faf
Revises: 20451f64ded5
Create Date: 2020-08-20 10:35:15.220769

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4a09e2438faf'
down_revision = '20451f64ded5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'rev_s')
    op.drop_column('revisions', 'revision_id')
    op.drop_column('revisions', 'name')
    op.drop_column('revisions', 'rev_d')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('rev_d', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
    op.add_column('revisions', sa.Column('name', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('revisions', sa.Column('revision_id', mysql.VARCHAR(collation='utf8_bin', length=50), nullable=True))
    op.add_column('revisions', sa.Column('rev_s', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
