"""Added on delete cascade to users

Revision ID: 5ab7db83336b
Revises: 4a09e2438faf
Create Date: 2020-08-29 11:16:02.870228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ab7db83336b'
down_revision = '4a09e2438faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_roles_ibfk_2', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_ibfk_1', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'role', ['role_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_ibfk_1', 'user_roles', 'users', ['user_id'], ['id'])
    op.create_foreign_key('user_roles_ibfk_2', 'user_roles', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###
