"""Added file_path to revissions

Revision ID: 5bd2bc08c098
Revises: c1a6943b3052
Create Date: 2020-08-03 12:46:26.798151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bd2bc08c098'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('file_path', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'file_path')
    # ### end Alembic commands ###
