"""Uprava tabulky revize

Revision ID: e7bcb5bfc3cd
Revises: beba115dce90
Create Date: 2020-08-04 14:09:55.702892

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e7bcb5bfc3cd'
down_revision = 'beba115dce90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('revisions', 'file_path')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revisions', sa.Column('file_path', mysql.VARCHAR(collation='utf8_bin', length=256), nullable=True))
    # ### end Alembic commands ###
